stages:
  - test

test:
  stage: test
  needs: []
  tags:
    - u60
    - docker
    - gpu
  image: tandav/pitch-detectors:12.6.2-cudnn-devel-ubuntu24.04-python3.12@sha256:665b04e9a86d95b1b57175e582d66f0b6cdcda2accd7593845697a4021bd4c46
  cache:
    key: $CI_PROJECT_NAME
    paths:
      - .cache/
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
    RUFF_CACHE_DIR: "$CI_PROJECT_DIR/.cache/ruff_cache"
    MYPY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/mypy_cache"
    PITCH_DETECTORS_SPICE_MODEL_PATH: /models/spice_model
    PITCH_DETECTORS_PENN_CHECKPOINT_PATH: /models/fcnf0++.pt
  script:
    - export $(grep -v '^#' $S3_ENV | xargs) && python scripts/download_models.py
    - pytest --cov pitch_detectors --cov-report term --cov-report xml --junitxml report.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml

lint:
  stage: test
  tags:
    - u61
    - docker
  needs: []
  image: python:3.12@sha256:fce9bc7648ef917a5ab67176cf1c7eb41b110452e259736144bc22f32f3aa622
  variables:
    PIP_INDEX_URL: https://pypi.tandav.me/index/
  script:
    - pip install pre-commit
    - pre-commit run --all-files
