version: '3'
dotenv: ['.env']
env:
  UBUNTU_VERSION: 24.04
  CUDA_VERSION: 12.6.2
  PYTHON_VERSION: 3.12
  UV_IMAGE: ghcr.io/astral-sh/uv:0.5.4@sha256:5436c72d52c9c0d011010ce68f4c399702b3b0764adcf282fe0e546f20ebaef6
  BASE_IMAGE_CUDA_SHA256: 431b2307f69f41ca51503a6103be3b5c52dcfad18b201af7f12349a0cca35a4e
  BASE_IMAGE_CUDA: nvidia/cuda:{{.CUDA_VERSION}}-cudnn-devel-ubuntu{{.UBUNTU_VERSION}}@sha256:{{.BASE_IMAGE_CUDA_SHA256}}
  BASE_IMAGE: tandav/pitch-detectors-base:{{.CUDA_VERSION}}-cudnn-devel-ubuntu{{.UBUNTU_VERSION}}-python{{.PYTHON_VERSION}}
  IMAGE: tandav/pitch-detectors:{{.CUDA_VERSION}}-cudnn-devel-ubuntu{{.UBUNTU_VERSION}}-python{{.PYTHON_VERSION}}
  MODEL_PATH_SPICE: /mnt/sg8tb1/downloads-archive/libmv-data/spice_model
  MODEL_PATH_PENN: /mnt/sg8tb1/downloads-archive/libmv-data/fcnf0++.pt
tasks:
  build-base:
    cmd: >
        docker build
        --build-arg BASE_IMAGE_CUDA=$BASE_IMAGE_CUDA
        --tag $BASE_IMAGE
        --file docker/base.dockerfile .

  push-base:
    cmd: docker push {{.BASE_IMAGE}}

  build:
    deps: [build-base]
    cmd: >
      docker build
      --build-arg="BASE_IMAGE=$BASE_IMAGE"
      --build-arg="UV_IMAGE=$UV_IMAGE"
      --tag $IMAGE
      --file docker/pitch-detectors.dockerfile .

  push:
    cmd: docker push $IMAGE

  test:
    deps: [build]
    cmd: >
      docker run --rm -t --gpus all
      -v $MODEL_PATH_SPICE:/spice_model:ro
      -v $MODEL_PATH_PENN:/fcnf0++.pt:ro
      $IMAGE
      uv run
      pytest -v

  test-no-docker:
    cmd: uv run pytest -v

  bumpver:
    desc: 'Bump version. Pass --<part>. Usage example: task bumpver -- --minor'
    cmds:
      - uv run bumpver update --no-fetch {{.CLI_ARGS}}

  evaluation:
    deps: [build]
    cmd: >
      docker run --rm -t --gpus all
      -e PITCH_DETECTORS_GPU=true
      -e REDIS_URL={{.REDIS_URL}}
      -v /media/tandav/sg8tb1/downloads-archive/f0-datasets:/app/f0-datasets:ro
      {{.IMAGE}}
      python -m pitch_detectors.evaluation

  table:
    cmd: uv run python -m pitch_detectors.evaluation.table
