name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: install dependencies
        run: python3 -m pip install .[dev]

      - name: test
        run: pytest --cov pitch_detectors --cov-fail-under=90

  publish-to-pypi-and-github-release:
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pypa/build
        run: python -m pip install --upgrade setuptools build twine

      - name: Build a source tarball and wheel
        run: python -m build .

      - name:
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*

      - name: Github Release
        uses: softprops/action-gh-release@v1
