name: ci

on: push

jobs:
  test:
    runs-on: [self-hosted, gpu]
    steps:
      - uses: actions/checkout@v3

      - name: test gpu is available
        run: nvidia-smi

      - name: build image
        run: make build

      - name: test
        run: make test

      - name: test-no-gpu
        run: make test-no-gpu

  publish-to-pypi-and-github-release:
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pypa/build
        run: python -m pip install --upgrade setuptools build twine

      - name: Build a source tarball and wheel
        run: python -m build .

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*

      # doesn't work in private repos
      # - name: Github Release
      #   uses: softprops/action-gh-release@v1
